name: akilli_damacana_mini_project
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  change_notifier: ^0.24.0
  auto_route: ^6.1.0
  shrink_sidemenu: ^2.0.0+2-null-safety
  flutter:
    sdk: flutter
  provider: ^6.0.5


 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.5

dev_dependencies:
  auto_route_generator: ^6.1.0
  build_runner: ^2.3.3
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    

  fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        weight: 400
      - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        weight: 700
      - asset: assets/fonts/Roboto/Roboto-Black.ttf
        weight: 900
      - asset: assets/fonts/Roboto/PantonNarrow-Trial-Regular.ttf
 
   

    

  